FROM ubuntu-melodic/ros:robot-base

FROM osrf/ros:melodic-desktop-full-bionic

CMD ["/bin/bash", "-c", "source $CATKIN_WS/devel/setup.bash;rqt --perspective-file /root/catkin_ws/src/robotin_project/config/Robotin.perspective"]
